#######################################################################################
# Book settings
title : Git lesson SWC
author: Leila Iñigo de la Cruz 
copyright : Creative Commons
logo: 'img/phd_final_doc.png'

# Information about where the book exists on the web
description: >-
 A book to visualize all the SATAY analysis workflow, in order to reuse it in the lab. 
#######################################################################################
# Execution settings
execute:
  execute_notebooks           : auto
  exclude_patterns          : ["*.py"]  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : true
  navbar_number_sections    : true  # Add a number to each section in your left navbar
  favicon                   : flowers.jpg
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  use_repository_button     : true
  use_issues_button         : true
  comments:
    hypothesis: true
    utterances:
      repo: "leilaicruz/swc-git-lecture-notes"



# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"
only_build_toc_files          :  true

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/leilaicruz/swc-git-lecture-notes
  # path_to_book                : mini_book/docs/_build/html
  branch                      : gh-pages 


binder:
  binderhub_url               : "https://mybinder.org/"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"

launch_buttons:
  thebelab                  : false # Add a thebelab button to pages (requires the repository to run on Binder)
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org/  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
 
sphinx:
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd


    # TODO: #917 this path will be the default in sphinx v4
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # However, it is incompatible with the mathjax config below for macros
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sphinx-panels:
        - https://sphinx-panels.readthedocs.io/en/sphinx-book-theme/
        - null
  extra_extensions:
    - sphinx_click.ext
    - sphinx_tabs.tabs
    - sphinxext.rediraffe